@url=https://localhost:5001
@AuthorizationToken=

## Health

### Get Health
GET {{url}}/api/health
Content-Type: application/json

## Transaction
### Add Transaction
POST {{url}}/api/transaction
Authorization: Bearer {{AuthorizationToken}}
Content-Type: application/json

{
    "MainCategory": "Food & Beverage",
    "SubCategory": "Food & Beverage",
    "TransactionDate": "2024-02-01T11:41:32.123Z",
    "Notes": "Ereakfast",
    "PaymentMethod": "Cash",
    "PaymentAmount": 250.00
}

### Get Transactions
@sortBy=paymentAmount
@sortOrder=1
@currentPage=1
@pageSize=
@startDate=
@endDate=
@mainCategory=
@subCategory=
@paymentMethod=
@startPaymentAmount=
@endPaymentAmount=

GET {{url}}/api/transaction?startDate={{startDate}}&endDate={{endDate}}&mainCategory={{mainCategory}}&subCategory={{subCategory}}&paymentMethod={{paymentMethod}}&startPaymentAmount={{startPaymentAmount}}&endPaymentAmount={{endPaymentAmount}}&sortBy={{sortBy}}&sortOrder={{sortOrder}}&currentPage={{currentPage}}&pageSize={{pageSize}}
Authorization: Bearer {{AuthorizationToken}}
Content-Type: application/json

### Get Transaction Page Size
@pageSize=10
GET {{url}}/api/transaction/pageSize?startDate={{startDate}}&endDate={{endDate}}&mainCategory={{mainCategory}}&subCategory={{subCategory}}&paymentMethod={{paymentMethod}}&startPaymentAmount={{startPaymentAmount}}&endPaymentAmount={{endPaymentAmount}}&pageSize={{pageSize}}
Authorization: Bearer {{AuthorizationToken}}
Content-Type: application/json

### Get Transaction Detail
@transactionId=191e32d6fa7c46449bff507f61763b66
GET {{url}}/api/transaction/detail?transactionId={{transactionId}}
Authorization: Bearer {{AuthorizationToken}}
Content-Type: application/json

### Update Transaction Detail
PATCH {{url}}/api/transaction
Authorization: Bearer {{AuthorizationToken}}
Content-Type: application/json

{
    "TransactionId": "191e32d6fa7c46449bff507f61763b66",
    "MainCategory": "Food & Beverage",
    "SubCategory": "Food & Beverage",
    "TransactionDate": "2024-02-01T11:41:32.123Z",
    "Notes": "Breakfast",
    "PaymentMethod": "Cash",
    "PaymentAmount": 150.00,
    "ModifiedUTCDateTime": "2024-02-27T10:52:17.145Z"
}

### Delete Transaction
DELETE {{url}}/api/transaction/191e32d6fa7c46449bff507f61763b66
Authorization: Bearer {{AuthorizationToken}}
Content-Type: application/json

